language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
script:
  - make lint
  - make test-unit
